name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18'
    - run: go build -v -o main ./...
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: main